const questions = [
    {
        id: 1,
        question: "What's your project name?",
        placehoder: "Which project this build belong to?",
        summaryKeyValue: "Project",
        isReleaseKey: true,
        isReleaseNoteKey: false,
        isLongInput: false
    },
    {
        id: 2,
        question: "What is the purpose of the build?",
        placehoder: "Explain in short what is this build about like release summary",
        summaryKeyValue: "Requirement",
        isReleaseKey: true,
        isReleaseNoteKey: true,
        isLongInput: true,
    },
    {
        id: 3,
        question: "Do you have jira id?",
        placehoder: "Add jira link or confluence link",
        summaryKeyValue: "Jira",
        isReleaseKey: true,
        isReleaseNoteKey: true,
        isLongInput: false,
    },
    {
        id: 4,
        question: "What is the branch name?",
        placehoder: `Should follow "dev-<dev-name>-feature-name" syntax`,
        summaryKeyValue: "Branch Name",
        isReleaseKey: true,
        isReleaseNoteKey: false,
        isLongInput: false,
    },
    {
        id: 5,
        question: "Have you synced branch with master?",
        placehoder: `git fetch origin master/main?`,
        summaryKeyValue: "Synced with master",
        isReleaseKey: true,
        isReleaseNoteKey: false,
        isLongInput: false,
    },
    {
        id: 5,
        question: "Is dev unit testing done for this feature?",
        placehoder: "Are enough cases covered? Any edge cases?",
        summaryKeyValue: "Dev Unit testing",
        isReleaseKey: true,
        isReleaseNoteKey: false,
        isLongInput: false,
    },
    {
        id: 6,
        question: "Do we have QA sign-off?",
        placehoder: "",
        summaryKeyValue: "QA sign-off",
        isReleaseKey: true,
        isReleaseNoteKey: false,
        isLongInput: false,
    },
    {
        id: 7,
        question: "Are there any DB changes?",
        placehoder: "",
        summaryKeyValue: "DB Changes",
        isReleaseKey: true,
        isReleaseNoteKey: false,
        isLongInput: true,
    },
    {
        id: 8,
        question: "Are there any Saparate CSS/JS/Images changes?",
        placehoder: "",
        summaryKeyValue: "Any CSS/JS/Images",
        isReleaseKey: true,
        isReleaseNoteKey: false,
        isLongInput: true,
    },
    {
        id: 9,
        question: "Any remarks you think should be added?",
        placehoder: "",
        summaryKeyValue: "Note",
        isReleaseKey: true,
        isReleaseNoteKey: true,
        isLongInput: true,
    }
];

export default questions;